-- MySQL Script generated by MySQL Workbench
-- 02/21/17 12:12:58
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema homeworkSQL
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema homeworkSQL
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `homeworkSQL` DEFAULT CHARACTER SET utf8 ;
USE `homeworkSQL` ;

-- -----------------------------------------------------
-- Table `homeworkSQL`.`developers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homeworkSQL`.`developers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `join_date` DATE NULL,
  
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homeworkSQL`.`skills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homeworkSQL`.`skills` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homeworkSQL`.`developers_skills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homeworkSQL`.`developers_skills` (
  `developers_id` INT NOT NULL,
  `skills_id` INT NOT NULL,
  PRIMARY KEY (`developers_id`, `skills_id`),
  INDEX `fk_developers_has_skills_skills1_idx` (`skills_id` ASC),
  INDEX `fk_developers_has_skills_developers_idx` (`developers_id` ASC),
  CONSTRAINT `fk_developers_skills_developers`
    FOREIGN KEY (`developers_id`)
    REFERENCES `homeworkSQL`.`developers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_developers_skills_skills1`
    FOREIGN KEY (`skills_id`)
    REFERENCES `homeworkSQL`.`skills` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homeworkSQL`.`companies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homeworkSQL`.`companies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homeworkSQL`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homeworkSQL`.`customers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homeworkSQL`.`projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homeworkSQL`.`projects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `companies_id` INT NOT NULL,
  `customers_id` INT NOT NULL,
  PRIMARY KEY (`id`, `companies_id`, `customers_id`),
  INDEX `fk_projects_companies1_idx` (`companies_id` ASC),
  INDEX `fk_projects_customers1_idx` (`customers_id` ASC),
  CONSTRAINT `fk_projects_companies1`
    FOREIGN KEY (`companies_id`)
    REFERENCES `homeworkSQL`.`companies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projects_customers1`
    FOREIGN KEY (`customers_id`)
    REFERENCES `homeworkSQL`.`customers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homeworkSQL`.`projects_developers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homeworkSQL`.`projects_developers` (
  `projects_id` INT NOT NULL,
  `developers_id` INT NOT NULL,
  PRIMARY KEY (`projects_id`, `developers_id`),
  INDEX `fk_projects_has_developers_developers1_idx` (`developers_id` ASC),
  UNIQUE INDEX `projects_id_UNIQUE` (`projects_id` ASC),
  UNIQUE INDEX `developers_id_UNIQUE` (`developers_id` ASC),
  CONSTRAINT `fk_projects_has_developers_projects1`
    FOREIGN KEY (`projects_id`)
    REFERENCES `homeworkSQL`.`projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projects_has_developers_developers1`
    FOREIGN KEY (`developers_id`)
    REFERENCES `homeworkSQL`.`developers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
